### ISSUE TITLE
Look into `PytestUnraisableExceptionWarning` during tests

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/localtileserver#42]
```
  /opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function TileServerThread.__del__ at 0x7fb88d4b2550>
  
  Traceback (most recent call last):
    File "/home/runner/work/localtileserver/localtileserver/localtileserver/server.py", line 122, in __del__
      self.shutdown()
    File "/home/runner/work/localtileserver/localtileserver/localtileserver/server.py", line 118, in shutdown
      if self.is_alive():
    File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/threading.py", line 1134, in is_alive
      assert self._initialized, "Thread.__init__() not called"
  AssertionError: Thread.__init__() not called
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

```

To do:

- [x] What test is causing this issue?
- [x] What code in that test is problematic?
- [x] Is this serious?
- [x] Can this be resolved?

**Comment by banesullivan** [comment]
>  What test is causing this issue?
> What code in that test is problematic?

The issue was the `test_create_tile_client_bad` test where I catch specific errors when creating a `TileServerThread` instance. The `__init__` of `TileServerThread` performed a fe value checks before initializing the actual `Thread`:

https://github.com/banesullivan/localtileserver/blob/f2c9c60fdcbf0b11f389937c5ed289a9d0da0c4a/localtileserver/server.py#L82-L91

On errors, the initialization would never happen on garbage collection the `__del__` operator override would be called, calling:

https://github.com/banesullivan/localtileserver/blob/f2c9c60fdcbf0b11f389937c5ed289a9d0da0c4a/localtileserver/server.py#L121

Which is what caused the error.

> Is this serious?

Not at all

> Can this be resolved?

Done. See associated commit
